"""docx-knife: AI-safe DOCX patch engine with stable paragraph anchors."""

from __future__ import annotations

from ._models import (
    AnyEditOperation,
    ContentItem,
    ContentRef,
    ContentSourceCommand,
    ContentSourceFile,
    ContentSourceJsonPath,
    DeletePara,
    DeleteText,
    EditOperation,
    EditResult,
    InsertParaAfter,
    InsertParaBefore,
    InsertTextAfter,
    InsertTextBefore,
    OperationResult,
    Pagination,
    ParagraphId,
    ParagraphInfo,
    ParagraphListResult,
    ParagraphLocation,
    ParagraphMatchInfo,
    ParagraphSearchResult,
    ReplacePara,
    ReplaceText,
    SaveResult,
    Selector,
    TableContext,
    TextMatch,
)
from ._schema import BATCH_SCHEMA, validate_batch
from .content import ContentResolverConfig
from .document import Document
from .errors import (
    AmbiguousTextMatchError,
    BatchOperationError,
    DocumentNotFoundError,
    DocxKnifeError,
    InvalidContentError,
    InvalidDocumentError,
    InvalidPatternError,
    ParagraphNotFoundError,
    SourceChangedError,
    TextNotFoundError,
    UnsupportedStructureError,
    ValidationError,
)
from .paragraph import Paragraph

__version__ = "0.1.0"

__all__ = [
    "BATCH_SCHEMA",
    "AmbiguousTextMatchError",
    "AnyEditOperation",
    "BatchOperationError",
    "ContentItem",
    "ContentRef",
    "ContentResolverConfig",
    "ContentSourceCommand",
    "ContentSourceFile",
    "ContentSourceJsonPath",
    "DeletePara",
    "DeleteText",
    "Document",
    "DocumentNotFoundError",
    "DocxKnifeError",
    "EditOperation",
    "EditResult",
    "InsertParaAfter",
    "InsertParaBefore",
    "InsertTextAfter",
    "InsertTextBefore",
    "InvalidContentError",
    "InvalidDocumentError",
    "InvalidPatternError",
    "OperationResult",
    "Pagination",
    "Paragraph",
    "ParagraphId",
    "ParagraphInfo",
    "ParagraphListResult",
    "ParagraphLocation",
    "ParagraphMatchInfo",
    "ParagraphNotFoundError",
    "ParagraphSearchResult",
    "ReplacePara",
    "ReplaceText",
    "SaveResult",
    "Selector",
    "SourceChangedError",
    "TableContext",
    "TextMatch",
    "TextNotFoundError",
    "UnsupportedStructureError",
    "ValidationError",
    "__version__",
    "validate_batch",
]
